# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.4

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/rafa/Proyectos/system_monitor

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/rafa/Proyectos/system_monitor

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rafa/Proyectos/system_monitor/CMakeFiles /home/rafa/Proyectos/system_monitor//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rafa/Proyectos/system_monitor/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SysMon-CPP

# Build rule for target.
SysMon-CPP: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SysMon-CPP
.PHONY : SysMon-CPP

# fast build rule for target.
SysMon-CPP/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SysMon-CPP.dir/build.make CMakeFiles/SysMon-CPP.dir/build
.PHONY : SysMon-CPP/fast

src/Display.o: src/Display.cpp.o
.PHONY : src/Display.o

# target to build an object file
src/Display.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SysMon-CPP.dir/build.make CMakeFiles/SysMon-CPP.dir/src/Display.cpp.o
.PHONY : src/Display.cpp.o

src/Display.i: src/Display.cpp.i
.PHONY : src/Display.i

# target to preprocess a source file
src/Display.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SysMon-CPP.dir/build.make CMakeFiles/SysMon-CPP.dir/src/Display.cpp.i
.PHONY : src/Display.cpp.i

src/Display.s: src/Display.cpp.s
.PHONY : src/Display.s

# target to generate assembly for a file
src/Display.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SysMon-CPP.dir/build.make CMakeFiles/SysMon-CPP.dir/src/Display.cpp.s
.PHONY : src/Display.cpp.s

src/NetworkClient.o: src/NetworkClient.cpp.o
.PHONY : src/NetworkClient.o

# target to build an object file
src/NetworkClient.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SysMon-CPP.dir/build.make CMakeFiles/SysMon-CPP.dir/src/NetworkClient.cpp.o
.PHONY : src/NetworkClient.cpp.o

src/NetworkClient.i: src/NetworkClient.cpp.i
.PHONY : src/NetworkClient.i

# target to preprocess a source file
src/NetworkClient.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SysMon-CPP.dir/build.make CMakeFiles/SysMon-CPP.dir/src/NetworkClient.cpp.i
.PHONY : src/NetworkClient.cpp.i

src/NetworkClient.s: src/NetworkClient.cpp.s
.PHONY : src/NetworkClient.s

# target to generate assembly for a file
src/NetworkClient.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SysMon-CPP.dir/build.make CMakeFiles/SysMon-CPP.dir/src/NetworkClient.cpp.s
.PHONY : src/NetworkClient.cpp.s

src/Parser.o: src/Parser.cpp.o
.PHONY : src/Parser.o

# target to build an object file
src/Parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SysMon-CPP.dir/build.make CMakeFiles/SysMon-CPP.dir/src/Parser.cpp.o
.PHONY : src/Parser.cpp.o

src/Parser.i: src/Parser.cpp.i
.PHONY : src/Parser.i

# target to preprocess a source file
src/Parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SysMon-CPP.dir/build.make CMakeFiles/SysMon-CPP.dir/src/Parser.cpp.i
.PHONY : src/Parser.cpp.i

src/Parser.s: src/Parser.cpp.s
.PHONY : src/Parser.s

# target to generate assembly for a file
src/Parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SysMon-CPP.dir/build.make CMakeFiles/SysMon-CPP.dir/src/Parser.cpp.s
.PHONY : src/Parser.cpp.s

src/SystemInfo.o: src/SystemInfo.cpp.o
.PHONY : src/SystemInfo.o

# target to build an object file
src/SystemInfo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SysMon-CPP.dir/build.make CMakeFiles/SysMon-CPP.dir/src/SystemInfo.cpp.o
.PHONY : src/SystemInfo.cpp.o

src/SystemInfo.i: src/SystemInfo.cpp.i
.PHONY : src/SystemInfo.i

# target to preprocess a source file
src/SystemInfo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SysMon-CPP.dir/build.make CMakeFiles/SysMon-CPP.dir/src/SystemInfo.cpp.i
.PHONY : src/SystemInfo.cpp.i

src/SystemInfo.s: src/SystemInfo.cpp.s
.PHONY : src/SystemInfo.s

# target to generate assembly for a file
src/SystemInfo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SysMon-CPP.dir/build.make CMakeFiles/SysMon-CPP.dir/src/SystemInfo.cpp.s
.PHONY : src/SystemInfo.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SysMon-CPP.dir/build.make CMakeFiles/SysMon-CPP.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SysMon-CPP.dir/build.make CMakeFiles/SysMon-CPP.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SysMon-CPP.dir/build.make CMakeFiles/SysMon-CPP.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... SysMon-CPP"
	@echo "... src/Display.o"
	@echo "... src/Display.i"
	@echo "... src/Display.s"
	@echo "... src/NetworkClient.o"
	@echo "... src/NetworkClient.i"
	@echo "... src/NetworkClient.s"
	@echo "... src/Parser.o"
	@echo "... src/Parser.i"
	@echo "... src/Parser.s"
	@echo "... src/SystemInfo.o"
	@echo "... src/SystemInfo.i"
	@echo "... src/SystemInfo.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

